# Generated by Django 4.1.4 on 2022-12-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_category_options_product_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.SlugField(),
        ),
    ]
