# Generated by Django 4.1.4 on 2023-02-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="email",
            field=models.CharField(default="noemail@mail.com", max_length=255),
        ),
    ]
